// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5hKV0RdQU73XHvMFfq8439RC3OGheu1E',
    appId: '1:1077787230215:web:b651fab11ca47ad48beaa2',
    messagingSenderId: '1077787230215',
    projectId: 'tocofood-21b4d',
    authDomain: 'tocofood-21b4d.firebaseapp.com',
    storageBucket: 'tocofood-21b4d.appspot.com',
    measurementId: 'G-L8SQCEXSJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIlQWX7kOcOo3AHdlTnidCXpBoVxWs06E',
    appId: '1:1077787230215:android:6c203e3a8cd293318beaa2',
    messagingSenderId: '1077787230215',
    projectId: 'tocofood-21b4d',
    storageBucket: 'tocofood-21b4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj3liJ8MdqLIApE8HEnlihYyOQNIG353g',
    appId: '1:1077787230215:ios:517a47ed19b7deeb8beaa2',
    messagingSenderId: '1077787230215',
    projectId: 'tocofood-21b4d',
    storageBucket: 'tocofood-21b4d.appspot.com',
    iosBundleId: 'com.example.totofood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj3liJ8MdqLIApE8HEnlihYyOQNIG353g',
    appId: '1:1077787230215:ios:722783248ed2aad58beaa2',
    messagingSenderId: '1077787230215',
    projectId: 'tocofood-21b4d',
    storageBucket: 'tocofood-21b4d.appspot.com',
    iosBundleId: 'com.example.totofood.RunnerTests',
  );
}
